### ISSUE TITLE
Panel dla myszy ...

### ISSUE THREAD

**Issue by kashkash18** [Mariusz89B/script.mtvguide#1]
Witaj.
Po zaznaczeniu w ustawieniach "Panel dla myszy i urządzeń dotykowych" nie pojawia się dolna belka.

Android 9.0 Kodi 18.5

**Comment by Mariusz89B** [comment]
Potrzeba cos poprawić czy działa prawidłowo?

**Comment by kashkash18** [comment]
Tak , problem jest cały czas . Zamkiem tutaj temat gdyż to samo napisałem na PTW.

**Comment by Mariusz89B** [comment]
Ok sprawdze to.

**Comment by kashkash18** [comment]
Wersja wtyczki 8.1.976 , na obu skinach

**Comment by Mariusz89B** [comment]
Znalazlem blad w skorkach za niedlugo bedzie poprawka.
