### ISSUE TITLE
No link

### ISSUE THREAD

**Issue by ColtCarson45** [Mariusz89B/script.mtvguide#12]
Hi,
I looked in the link in wiki, and I cannot find the correct repository, I downloaded the file and looked on add on and can’t find it. I’m sorry for this inconvenience but could you give me step by step ways to get the url please?
Thanks

**Comment by Mariusz89B** [comment]
Hi @ColtCarlson45, 

I see that it can be a little bit tricky to find in Wiki, you need to click on the text "download mods-kodi repository", here is the URL link for the repository:

https://github.com/Mariusz89B/mods-kodi/raw/master/repository.mods-kodi/repository.mods-kodi-1.0.1.zip

**Comment by ColtCarson45** [comment]
Thank you,
Is this what I put in file manager in Kodi?

**Comment by Mariusz89B** [comment]
@ColtCarson45 > Thank you, Is this what I put in file manager in Kodi?

I don't think that is possible with Github URL links, you need to manually download and install the repository zip file. Let me check and I will get back to you.

## Installation
To install the repository, you must manually download and install the repository addon.

Download https://github.com/Mariusz89B/mods-kodi/raw/master/repository.mods-kodi/repository.mods-kodi-1.0.1.zip

1. Goto your Addons screen in Kodi
2. Select "Install from Zip" and select the repository.mods-kodi-1.0.1.zip file you downloaded
3. The repository is now installed and you can now install the various addons available.

**Comment by ColtCarson45** [comment]
How could I do that? I’m sorry I’m on fire stick  and haven’t had to do
something like that before

**Comment by Mariusz89B** [comment]
@ColtCarson45 I edited my last post with instructions:
https://github.com/Mariusz89B/script.mtvguide/issues/12#issuecomment-1001172085

**Comment by ColtCarson45** [comment]
Thank you!

**Comment by Mariusz89B** [comment]
I will add those instructions to the Wiki thread.

**Comment by ColtCarson45** [comment]
Awesome, thanks!

**Comment by Mariusz89B** [comment]
Updated:
https://github.com/Mariusz89B/script.mtvguide/wiki
