### ISSUE TITLE
Recording doesn't work

### ISSUE THREAD

**Issue by lars-rasmussen** [Mariusz89B/script.mtvguide#14]
### Describe the bug

When I try to record a 35-minute long programme, it starts the recording as planned. But then it finishes within a minute and doesn't produce any file in the recordings folder.

## Expected Behavior

I would expect the programme to be recorded in 35 minutes and then be available in as a file in the recordings folder.

## Actual Behavior

The recording finishes within a minute and doesn't produce any file in the recordings folder.

## Possible Fix

The debuglog shows the same erorr message many times: "ERROR: too short recording". This might indicate the problem.

### To Reproduce

1. I installed your addon from the zip file in the following link: https://github.com/Mariusz89B/mods-kodi/raw/master/repository.mods-kodi/repository.mods-kodi-1.0.1.zip
2. I followed the configuration tutorial, i.e. logged in to WP Pilot (free account), chose my EPG and installed the recording applications when asked to do so. Afterwards Kodi requested a restart.
3. When Kodi had restarted I followed the procedure shown in the screenshots below.

### Debuglog

https://paste.ubuntu.com/p/pTtPxt28ng/
### Screenshots 
A collection of screenshots that documents my procedure:

https://imgur.com/a/mev9kLp

## Additional context or screenshots (if appropriate)

I have ffmpeg.exe installed in C:\ffmpeg\bin\ffmpeg.exe, but your addon has selected the custom path C:\Users\[MY USERNAME]\AppData\Roaming\Kodi\userdata\addon_data\script.mtvguide\record_app\ffmpeg.exe. I have since tried to set C:\ffmpeg\bin\ffmpeg.exe in the IMPORT FFMPEG path, but this has not resolved the issue.

I have set the recordings folder as C:\Recordings\.

And I will also note that playback of the WP Pilot channels works flawlessly. But I cannot record them.

### Your Environment
Used Operating system:

 - Windows 10

 - Kodi version: 19.3.0

**Comment by Mariusz89B** [comment]
Server is returning Forbidden 403 HTTP Error, I'll try to see what it could be due to, might be that I need to update the headers.
`[https @ 000001b5c179e480] HTTP error 403 Forbidden\r\nhttps://stream-cdn-1.videostar.pl/5/smil:basic/playlist.m3u8?t2=a721b1db196d4ba6a27fd47fe7c87c0b&t3=aaefc94ca3304e05aa3482bf1fc2ec3d&t5=&xxx: Server returned 403 Forbidden (access denied)`

**Comment by Mariusz89B** [comment]
@lars-rasmussen Should be recording now.
https://github.com/Mariusz89B/script.mtvguide/commit/26c0c2c04728870c3ed4edaf377b715f8a1510de

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.8.9_v30

**Comment by lars-rasmussen** [comment]
@Mariusz89B

It works now. Thank you so much. I managed to record a programme (Stepowa miłosz) using the 9.8.9_v30 beta release.

The debuglog is here:

https://paste.ubuntu.com/p/fyjX6sCgw2/

It should be noted that I used C:\ffmpeg\bin\ffmpeg.exe as the path in Import FFMPEG in the addon settings.

...

I am curious to know if you can work your magic so it can also work with channels from PlayerPL (TVN-owned). Using the PlayerPLmb addon from mbebe (https://github.com/mbebe/blomqvist) I created a m3u list that I have then imported in your addon. It contains the channels TVN, Metro, Eurosport 1 and Eurosport 2 (the first two are freely available, the last two sports channels are part of a current subscription I have).

Screenshorts showing how I made the m3u list:

https://imgur.com/a/5dOYg0l

Playback works as it should but when I try to record a programme from the Metro channel (Fani czterech kółek 14) it outputs the same error as before ("ERROR: too short recording").

The details are in the linked debuglog above. I hope that this being the same type of error makes it easy to solve.

Best regards
Lars

**Comment by Mariusz89B** [comment]
@lars-rasmussen Unfortunately, those mentioned TV services use DRM, the material is there with protected and not recordable/downloadable. I can't bypass the DRM as I would be breaking the law.
