### ISSUE TITLE
Zaprogramowane nagrania przestały działać.

### ISSUE THREAD

**Issue by nalewkababuni** [Mariusz89B/script.mtvguide#15]
### Describe the bug
Here is a clear and concise description of what the problem is:

Zaprogramowane nagrania przestały działać. Jestem na becie 9.9.4_v1 i problem pojawił się na którejś wersji beta 9.9.3. Załączam log z momentu po takim zaprogramowanym nagraniu, kiedy nie zadziałało.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Zaprogramowany program powinien zostać nagrany.

## Actual Behavior

Brak nagrania. Program, który powinien zostać nagrany, po kliknięciu na niego PPM traktowany jest jako nadal nagrywany. Trzeba kliknąć "Przerwij nagrywanie". Wtedy pojawia się na dysku plik o wielkości 0 bajtów z nazwą nagranego programu.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be obtained in m-TVGuide settings, database tab:
https://paste.ubuntu.com/p/RfqF2M4x5M/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.

m-TVGuide administration will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by nalewkababuni** [comment]
Zapomniałem dodać, że nagrywanie z archiwum działa normalnie. Działam na PlusX.

**Comment by Mariusz89B** [comment]
@nalewkababuni Literowka z mojej strony, sprawdz czy jest ok:
https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.4_v3

https://github.com/Mariusz89B/script.mtvguide/commit/71e31a60985bbabcd4e93a75d11fdd3824485810

**Comment by nalewkababuni** [comment]
Potwierdzam. Jest OK. Dzięki.
