### ISSUE TITLE
Zła nazwa pliku przy nagrywaniu.

### ISSUE THREAD

**Issue by nalewkababuni** [Mariusz89B/script.mtvguide#17]
## Bug report
https://paste.ubuntu.com/p/43fXFFs6xg/

### Describe the bug
Here is a clear and concise description of what the problem is:

Ustawiłem dwa nagrania programu na tym samym kanale. Jedno o 2 w nocy, drugie o 7 rano. Problem polega na tym, że obydwa nagrania mają tytuł tego drugiego. Dobra dam przykład jaki nagrywałem, bo będzie prościej wyjaśnić:
O_co_biega_2022-07-10_07-00.mpeg
O_co_biega_2022-07-10_07-00_part_2.mpeg
To są pliki jakie otrzymałem. Ten pierwszy powinien nazywać się:
O_co_biega_2022-07-10_02-00

Problem pojawił się od tej wersji w której pojawia się okienko z możliwością nadania nazwy plikowi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be obtained in m-TVGuide settings, database tab:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 10
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.

m-TVGuide administration will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Mariusz89B** [comment]
Gdy istnieję już zapisany plik o tej samej nazwie, to wtyczka automatycznie przypisuję numer kolejności w tym przypadku "part_2".

**Comment by nalewkababuni** [comment]
Ale wcześniej został wyemitowany odcinek O_co_biega_2022-07-10_02-00 o godzinie 2 w nocy. Został on nagrany, ale z nazwą 2022-07-10_07-00. Dlatego do nagrania zaprogramowanego na 7 rano zostało dodane &#34;part_2&#34;.  To jest ewidentny błąd, jeśli nadal nie dość dokładnie wyjaśniłem o co mi chodzi, to daj proszę znać. Może ująłem to zbyt chaotycznie. Postaram się wyjaśnić dokładniej.  
            
          
     
      
       
        Dnia 10 lipca 2022 17:40 Mariusz89B ***@***.***&gt; napisał(a):
       
    
       
         
 Gdy istnieję już zapisany plik o tej samej nazwie, to wtyczka automatycznie przypisuję numer kolejności w tym przypadku &#34;part_2&#34;.

**Comment by Mariusz89B** [comment]
Tak masz racje, zauwazylem blad. Sprawdz czy w tej wersji dziala poprawnie.
https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.623_v1

**Comment by nalewkababuni** [comment]
OK, przetestuję, ale będę mógł dać znać dopiero jutro rano.

**Comment by Mariusz89B** [comment]
> OK, przetestuję, ale będę mógł dać znać dopiero jutro rano.

Nie spieszy sie, dziekuje za zgloszenie bledu. :)

**Comment by nalewkababuni** [comment]
Spoko. Używam programu od lat. Jak coś to jeszcze jest pewna nieścisłość w tłumaczeniu, tak mi się przynajmniej wydaje. Chodzi o zakładkę Baza->Wyczyść bazę. Ta pozycja opisana jest po angielsku "Reseting the database will cause losing all settings, might be helpful in case of data have become corrupted", podczas gdy czyszczenie bazy nie usuwa wszystkich ustawień. Nie wiem czy to jest tak celowo opisane, ale dla mnie jest to mylące, tym bardziej, że często początkującym użytkownikom wtyczki jest radzone "wyczyść bazę". To co sobie taka zielonka pomyśli.

**Comment by Mariusz89B** [comment]
@nalewkababuni Wlasnie sie wczoraj nad tym zastanawialem, bedzie poprawka w nastepnej wersji:
https://github.com/Mariusz89B/script.mtvguide/wiki/Wiki#reset-database-runscriptcwdcleardbpy-clearall

**Comment by Mariusz89B** [comment]
@nalewkababuni Zauwazylem jeszcze inny blad w wersji beta.1 zwiazane z nazwa pliku, tutaj poprawka:
https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.623_v2

**Comment by nalewkababuni** [comment]
Przetestowane, działa jak powinno. Dzięki!

**Comment by Mariusz89B** [comment]
Super, dzieki! :)
