### ISSUE TITLE
Importing via cmore api doesn't work

### ISSUE THREAD

**Issue by Airbox79** [Mariusz89B/script.mtvguide#19]
### Describe the bug
Import channels via the cmore api doesn't work for some reason, Telia Play does. I'm using iptv-org as epg source.

## Expected Behavior
All channels from cmore shows up in the guide

## Actual Behavior
No channel at all shows up. If exported cmore addon m3u list is imported, some channels works, but some doesn't.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be obtained in m-TVGuide settings, database tab:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: LibreElec 10.0.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.

m-TVGuide administration will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Mariusz89B** [comment]
Hi, please provide a full debug log.

**Comment by Mariusz89B** [comment]
Probable cause is that epg channel names does not match basemap channel ids, please use add channel function to add missing channels.

https://github.com/Mariusz89B/script.mtvguide/wiki/Quickstart#add-channel

Please see Setup instructions.
https://github.com/Mariusz89B/script.mtvguide/wiki/Setup
