### ISSUE TITLE
WP Pilot 

### ISSUE THREAD

**Issue by djlosiu** [Mariusz89B/script.mtvguide#2]
Witam mógłbyś dodać Home tv i Music Box Polska bo jest w ofercie WP Pilot a w mtv-guide nie wczytuje.

**Comment by Mariusz89B** [comment]
Tak, mogę dodać jeśli są w epg.

**Comment by djlosiu** [comment]
Nie wiem co to oznacza że są w epg ale tu jest epg:
https://programtv.onet.pl/program-tv/tvr-hd-170 
https://programtv.onet.pl/program-tv/music-box-538

**Comment by Mariusz89B** [comment]
Podaj mi log, bo niemam premium w WP Pilot a musze sprawdzic nazwy kanalow. 

Bardziej mi chodzilo w epg z ktorego uzywasz.

**Comment by djlosiu** [comment]
https://paste.ubuntu.com/p/WkwKDdtd3z/ 
A epg używam z mtvguide.

**Comment by Mariusz89B** [comment]
Masz na mysli z mods-kodi?, mtvguide to wtyczka. :)

Przygotowalem wtyczke, teraz trzeba jeszcze dodac te kanaly do epg, sprobuje to zrobic jak znajde troche czasu, chyba ze popros kogos z adminow na forum by dodali.

**Comment by djlosiu** [comment]
Tak z mods-kodi źle napisałem.Ok nie spieszy się z tymi kanałami. :)

**Comment by djlosiu** [comment]
Kiedy będą te kanały?

**Comment by Mariusz89B** [comment]
Jutro o 16.

**Comment by djlosiu** [comment]
Dzięki za dodanie kanałów.
