### ISSUE TITLE
Nagrywanie z archiwum, problem z nazywaniem plików.

### ISSUE THREAD

**Issue by nalewkababuni** [Mariusz89B/script.mtvguide#20]
### Describe the bug
Zauważyłem, że nadanie własnej nazwy programowi, który chcę nagrać, nic nie daje. Po nagraniu program nadal ma domyślną nazwę.
Na przykładzie będzie prościej wyjaśnić. Mam do nagrania Columbo o godz. 20. Przesuwam czas rozpoczęcia nagrania na 19:45. W tym nowym okienku do nadawania nazwy nagrania pojawia się poprawna sugerowana nazwa programu: Columbo_2022-08-04_19-45.
Jednak nagrany program na dysku ma nazwę Columbo_2022-08-04_20-00.
Podobnie jest gdy spróbowalbym nadać nazwę nagraniu z "Columbo_2022-08-04_20-00" na "Columbo", to nagranie i tak będzie miało nazwę "Columbo_2022-08-04_20-00".

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debug log can be obtained in m-TVGuide settings, debug tab:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: 10
 - Kodi version: 19,4
 - m-TVGuide version: ostatnia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.

m-TVGuide administration will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Mariusz89B** [comment]
@nalewkababuni Sprawdz czy dziala, mi teraz wyswietla poprawna godzine w okienku nawet po jej przesunieciu i zapisuje wybrana nazwe.
https://github.com/Mariusz89B/script.mtvguide/commit/3a45dd67f32c42a908bd02e711b4eaf3f39bdcdf

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.626_v1

**Comment by nalewkababuni** [comment]
Nie, nadal nadawana jest domyślna nazwa, czyli "tytuł_rrrr-mm-dd_gg-mm". Sprawdzone na nagraniu z archiwum.

**Comment by Mariusz89B** [comment]
@nalewkababuni Faktycznie, pomylilem sie myslalem ze chodzi o nagrywanie, a nie sprawdzilem pobierania archiwum, tutaj poprawka.
https://github.com/Mariusz89B/script.mtvguide/commit/d43f554ddb0894da0fd3af9e2c3a8d1c86ea03ed

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.626_v2

**Comment by nalewkababuni** [comment]
OK, działa już nadawanie własnej nazwy pobraniom z archiwum. Potestuję jeszcze zaplanowane nagrania i dam znać jutro.
I jeszcze mam takie pytanie. Na TVS leci Colombo cztery razy dziennie. Czy istnieje metoda (działa tak w moim dekoderze do TV), żeby nagrać wszystkie odcinki przy jednokrotnym ustawieniu reguły? Takie ngraj wszytkie wystąpienia Colombo w całym epg, albo na danym kanale.

**Comment by Mariusz89B** [comment]
Jesli nazwa programu jest identyczna to powinno nagrac wszystkie odc. tego dnia jak dobrze pamietam.

**Comment by nalewkababuni** [comment]
Dobra, jest znowu błąd. Nie można ustawić przyszłego programu do nagrania. Robię jak zawsze, pojawia się standradowe okienko, gdy już zatwierdzam, ale nie pojawia się to okienko gdzie można nadać własną nazwę. Po wciśnięciu OK zaplanowany program nie wyróżnia się na liście jako planowany do nagrania.

**Comment by Mariusz89B** [comment]
~~Wywołaj błąd i podeślij mi log, sprawdze.
https://github.com/Mariusz89B/script.mtvguide/wiki/Wiki#upload-kodi-log-runscriptcwdloguploaderpy-primary~~

EDIT:
Znalazłem błąd, moja wina, literówka w kodzie, tu poprawka.
https://github.com/Mariusz89B/script.mtvguide/commit/0b9915892896251e61eec3bc6ffa43ec08b00647

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.626_v3

**Comment by nalewkababuni** [comment]
Działa. Udało się zaplanować nagranie.

**Comment by Mariusz89B** [comment]
Dziękuję za uwagę, zamykam wątek.
