### ISSUE TITLE
impossible to choose the stream

### ISSUE THREAD

**Issue by mifille** [Mariusz89B/script.mtvguide#21]
hello, 
thank you for your work but I cannot assign a stream to a program.
when I right click on a channel and then on "choose a stream" I can't find my streams because they are in a video staker addon.
if I put a channel in the favorites then it works but I cannot put 1000 channels in favorites and I need the favorites section for something else. 
Do you have a solution?
thank you in advance

**Comment by Mariusz89B** [comment]
Try generating a M3U playlist to use with m-TVGuide, most of Kodi addons offers such solutions.
