### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by nalewkababuni** [Mariusz89B/script.mtvguide#22]
### Describe the bug
Here is a clear and concise description of what the problem is:

Od wczoraj mam problemy ze strefą czasową. Widzę, że fix się pojawił ale po jego instalacji nadal nie dziala. Od kiedy pamiętam nie działało u mnie ustawienie automatyczna strefa czasowa i po każdym przesunięciu czasu musiałem dostosować to ręcznie. Teraz nie działa automatyczna, jak i manualna strefa czasowa. W każdym przypadku epg jest godzinę do tyłu. Oczywiście po każdej zmianie tego ustawienia robię "Wyczyść bazę".
Windows 10, Kodi 19.4.
Załączam log

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debug log can be obtained in m-TVGuide settings, debug tab:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.4
 - m-TVGuide version: ostatnia beta

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.

m-TVGuide administration will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by JayDee696969** [comment]
Timezone is still not working on latest version. Setting timezone manually still has no effect.

**Comment by JayDee696969** [comment]
I rolled back to version 9.9.628. Timezone works again on this version.

**Comment by nalewkababuni** [comment]
Done the same. This works.

**Comment by Mariusz89B** [comment]
@JayDee696969 @nalewkababuni Timezone bug should be fixed in latest version 9.9.630.
https://github.com/Mariusz89B/script.mtvguide/commit/7307f427e94250bcee41dec1b6689771e3a57b55

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.630

**Comment by nalewkababuni** [comment]
Forgot to write, no time lately, but this fix doesn't work for me. EPG is still one hour back. No matter if its on automatic or manual time zone. Tested latest beta each time database deleted. Maybe its something on my side, but what to do to fix it?

**Comment by Mariusz89B** [comment]
There are different types of epg, which one are you using, the one from kodiwpigulce?

**Comment by nalewkababuni** [comment]
epg.ovh/plar

**Comment by Mariusz89B** [comment]
Ok, let me check.

EDIT:
Your right, manual mode is still not working. I need to fix this.

**Comment by Mariusz89B** [comment]
@nalewkababuni Please see if this version is working properly. You can now use the guide reinitializing setting in context menu to reload the epg.
https://github.com/Mariusz89B/script.mtvguide/commit/8b073772ee3c1da8b22c0caeb8a6d3105af8dfa0

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.631_v2

**Comment by nalewkababuni** [comment]
Yes, now works fine. Thanks.
What is the purpose of reload epg in context menu? Does it mean that now I can do reload and do not need to remove database?

**Comment by Mariusz89B** [comment]
@nalewkababuni Yes thats right you can now reload the epg without resetting or removing the database, I also noted another issue some small fix added in v3.
https://github.com/Mariusz89B/script.mtvguide/commit/0657d41e3e9b5c6dd8410084fe084db0786c340f

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.631_v3

**Comment by Mariusz89B** [comment]
@nalewkababuni I found another issue for auto timezone, I fixed it in v4 and should be now working with all epgs including epg.ovh/plar.
https://github.com/Mariusz89B/script.mtvguide/commit/a161a7387345fadecb95e1b4816e7ca22a37077d

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.631_v4
