### ISSUE TITLE
EPG again

### ISSUE THREAD

**Issue by nalewkababuni** [Mariusz89B/script.mtvguide#24]
Today i updated Kodi to 19.5, have latest mtvguide 9.9.634 installed. The problem is epg again. I have auto time zone selected in settings, but the epg on the Kodi is +1 hour. I set manual time zone but nothing changed, still +1 hour. I don't think its because new version of Kodi, because i saw this error before updating to 19.5 and mtvguidemtvguide-9.9.633_v2. It was strange, because I was downloading tv show on 25.12 and epg was ok, on the 26.12 it is not. I made a screenshot on 25.12 and it looks like one epg is over the second.
I use Windows 10, Kodi 19.5, mtvguide 9.9.634 epg source:epg.ovh
![2022-12-26_170135](https://user-images.githubusercontent.com/30936261/209566328-e1cfa40c-6d37-4e29-94c1-210fe56ba9e8.jpg)

**Comment by Mariusz89B** [comment]
@nalewkababuni There are two different errors, first I assume your EPG provider has set the wrong timestamp (see below).

```
<programme start="20221226193000 +0100" stop="20221226200500 +0100" channel="TVP 1">
    <title lang="pl">Wiadomości</title>
```

![image](https://user-images.githubusercontent.com/67407746/209582079-5055583f-d815-498c-b881-b9e1732cf261.png)

So Wiadomosci is starting at 19.30, but the EPG is set for 19:30 +0100 which will result in 20:30.

As for the manual timezone setting in m-TVGuide, there is a fix provided below.
While selecting in settings EPG - Manually adjust timezone - 00:00 should now display the correct timestamp.
 
 https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.635_v1
 https://github.com/Mariusz89B/script.mtvguide/commit/b0399c817241f23642250fc6b8fca68ba7ea8933

**Comment by Mariusz89B** [comment]
@nalewkababuni Please try this version.
https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.635_v2

Use setting "Adjust to local timezone" then reinitilize the guide.

https://github.com/Mariusz89B/script.mtvguide/commit/3aab06e4306f0ccb15f15eb248363e7b6757b47b

**Comment by nalewkababuni** [comment]
No, still the same. I noticed the epg overlapping starts on the 25.12 at 7:00 and ends at 00:00. From 00:00 26.12 epg is +1 hour. Maybe there is something wrong in epg itself?


https://user-images.githubusercontent.com/30936261/209584921-d6363fd1-669c-4c78-9955-f08e035c273a.mp4

**Comment by Mariusz89B** [comment]
@nalewkababuni Have you reinitialized the guide?
Context menu - Reinitialize guide

But to answer your question, yes it seems to be some issues with the epg itself.

EDIT:
Another release with some fixes.
https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.635_v3

**Comment by nalewkababuni** [comment]
After installing v3 still the same. Yes, i have reinitialized the guide.

**Comment by Mariusz89B** [comment]
@nalewkababuni I'v made some changes in v5 on how m-TVGuide handles timezones,

Just to clarify m-TVGuide different timezone settings.

### 1.  Auto timezone

Automatically adjusts timezone to value provided in the EPG file.

eg. 

1. In this case below 19:30 +01:00 will result in 20:30. 

```
<programme start="20221226193000 +0100" stop="20221226200500 +0100" channel="TVP 1">
     <title lang="pl">Wiadomości</title>
 </programme>
```


2. But if a timezone is missing and the EPG auto correct the timezone itself then m-TVGuide will only read the timestamp resulting in 19:30.

```
<programme start="20221226193000" stop="20221226200500" channel="TVP 1">
    <title lang="pl">Wiadomości</title>
 </programme>
```

### 2. Adjust to local timezone

Adjust parsed date to local timezone. This will ignore the timezone found in the EPG file and set a timezone from system settings and correct itself for summer/winter time. 

```
<programme start="20221226193000 +0100" stop="20221226200500 +0100" channel="TVP 1">
     <title lang="pl">Wiadomości</title>
 </programme>
```

For timezone Poland/Warsaw this will add +01:00 to the EPG and result in 20:30.

### 3. Manually adjust timezone

Manually set a timezone value. 

> Manually adjust timezone have been fixed in 9.9.635


### 4. Result

I have tested `https://epg.ovh/pl.gz` with manually setting timezone to GMT 00:00 in settings, and the time is now displaying correctly.

![image](https://user-images.githubusercontent.com/67407746/209650324-0d589f72-bf7a-4c9a-8121-9fe4c5a675c6.png)

![screenshot00000](https://user-images.githubusercontent.com/67407746/209650263-4a64dbb0-7388-4dce-bf36-7ca4952f4896.png)


https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.635_v5
https://github.com/Mariusz89B/script.mtvguide/commit/69ddebbe7261f628282146aaa195b8b4ea426cd9

**Comment by nalewkababuni** [comment]
I confirm. Manually setting timezone to GMT 00:00 works. Thanks.

**Comment by Mariusz89B** [comment]
> I confirm. Manually setting timezone to GMT 00:00 works. Thanks.

I've got confirmation from @sky02 that an update broke the epg yesterday.

![Screenshot_20221227_161607_Discord](https://user-images.githubusercontent.com/67407746/209687862-48892b39-63ad-4da9-83be-1511865d91a8.jpg)

**Comment by nalewkababuni** [comment]
Tak, plar używam, ale zostaje przy nim, bo potrzebuję archiwum, a z tym manualnym ustawieniem działa ok.

**Comment by Mariusz89B** [comment]
https://github.com/Mariusz89B/script.mtvguide/commit/8751c031e93b3e0e80f8d9531f42324c2a5a6806
