### ISSUE TITLE
a correct working  tv guide and epg, but no livestreams possible at me

### ISSUE THREAD

**Issue by reneverlinden** [Mariusz89B/script.mtvguide#25]
I've installed epg and m3u from m3u4u correctly and after start the tv-guide appears on the screen correctly; however there is one problem: when i push on a channel for livestream, the program won't play (no livestream)  when i does the same on pvr simple client the tv-guide works fine and when i push on a channel then kodi plays the livestream, thus the m3u-links seem working perfectly, now my question is what could be the reason that there are no livestreams despite a correct tv-grid
and a good working epg? ?

**Comment by Mariusz89B** [comment]
Hi, please share a kodi log file so I can check what is wrong.

**Comment by reneverlinden** [comment]
[kodi.log](https://github.com/Mariusz89B/script.mtvguide/files/10561321/kodi.log)
hierbij de gevraagde kodi.log
here the kodi.log you've demanded

**Comment by Mariusz89B** [comment]
You are using an outdated version of m-TVGuide. `INFO <general>: CAddonMgr::ADDON::CAddonMgr::FindAddons: script.mtvguide v9.5.5`

Please install version 9.9.637.

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.637

**Comment by reneverlinden** [comment]
i've now installed the latest version of mtvguide  but as i 'v said  the tv-guide (grid), mpg and the m3u list perform very well , but i can't play livestream from the tv-guide , i 'v dropped a new kodilog file -thanks (the latest version is a significant approvement!)
[kodi.log](https://github.com/Mariusz89B/script.mtvguide/files/10568305/kodi.log)

**Comment by reneverlinden** [comment]
i've now installed the latest version of mtvguide but as i 'v said the tv-guide (grid), mpg and the m3u list perform very well , but i can't play livestream from the tv-guide , i 'v dropped a new kodilog file -thanks (the latest version is a significant approvement!)
[kodi.log](https://github.com/Mariusz89B/script.mtvguide/files/10568305/kodi.log)

**Comment by Mariusz89B** [comment]
It seems to be some sort of faulty configuration, maybe after the previous installation.

Could you try and delete all m-TVGuide settings and then run the built-in configurator? Maybe a fresh start will resolve your issues.

**Comment by reneverlinden** [comment]
on the kodi-logfile i 've found that mtvguide does not parse the url of logos  and the url of the channels
on my playlist; each url of logos begins with smb://... and the url of each channel on the playlist begins with http://....
they both perform well at pvr simple client and iptv merge but not in m-tvguide
[partof kodilogfile.txt](https://github.com/Mariusz89B/script.mtvguide/files/10581892/partof.kodilogfile.txt)

**Comment by reneverlinden** [comment]
as you've said i have changed some settings and... there is now playback ! - problem solved  
two minor problems :  I've set display logos:on but on the tv guide there come no chanellogos and where do I find the download for record_app  ?  thanks for your help to solve this issue!

**Comment by Mariusz89B** [comment]
@reneverlinden Might be that the channel icons are missing in the EPG. If you have custom channel icons you can add them yourself, please see https://github.com/Mariusz89B/script.mtvguide/wiki/Wiki#search-for-channel-logos-in-xmltv_logo_folder

You can download Record app in m-TVGuide settings.
https://github.com/Mariusz89B/script.mtvguide/wiki/Wiki#install-recording-applications-download_record_app

**Comment by reneverlinden** [comment]
thanks! case &  comment closed!
