### ISSUE TITLE
IPTV problem z nagrywaniem i archiwum.

### ISSUE THREAD

**Issue by nalewkababuni** [Mariusz89B/script.mtvguide#27]
### Describe the bug
Here is a clear and concise description of what the problem is:

Używam PlusX i od zeszłego tygodnia przestało mi działać archiwum, a także pobieranie z archiwum. Gostek tam coś podobno zmieniał, więc może jakieś parametry się pozmieniało. Załączam log, może uda się coś wyśledzić.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debug log can be obtained in m-TVGuide settings, debug tab:
Mam log zrobiony z ustawiń mtvguide w postaci wygenerowanego linka, tylko nie wiem czy jest bezpiecznie zamieszczać go w internecie...

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.1
 - m-TVGuide version: 9.9.637

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.

m-TVGuide administration will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Mariusz89B** [comment]
@nalewkababuni możesz mi wysłać log na mojego maila mariusz@mods-kodi.pl

**Comment by Mariusz89B** [comment]
Fixed in https://github.com/Mariusz89B/script.mtvguide/commit/5ced0a57976ab762946e6bbe01f293489a85a189

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.9.638
