### ISSUE TITLE
Wp pilot 

### ISSUE THREAD

**Issue by djlosiu** [Mariusz89B/script.mtvguide#7]
Wp pilot dalej nie działa nawet po wpisaniu netviapisessid i netviapisessval.

**Comment by Mariusz89B** [comment]
Maly blad z mojej strony, tutaj jest poprawka:
https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.4.6_v2

Daj znac czy jest ok.

https://github.com/Mariusz89B/script.mtvguide/commit/561bb7c0c0b0c1ab189524c9fc01d22141bddea1

**Comment by Mariusz89B** [comment]
Logowanie naprawione
https://github.com/Mariusz89B/script.mtvguide/commit/561bb7c0c0b0c1ab189524c9fc01d22141bddea1
