### ISSUE TITLE
Kodi crashing while choosing channel to play

### ISSUE THREAD

**Issue by onicniepytaj** [Mariusz89B/script.mtvguide#8]
### Describe the bug

Sometimes when one of the channels is chosen to play I can hear the double click and then kodi crashes. It reboots and kodi_crash.log is being created. This happens to me a few times a day. It's happening for the last couple of months

## Expected Behavior

Not to crash while double clicked (double click might not be relevant tho)

### Debuglog

This is the kodi_crash file generated during the last event. Kodi crashed around 12:05
[kodi_crash.log](https://github.com/Mariusz89B/script.mtvguide/files/7574515/kodi_crash.log)

## Additional context or screenshots (if appropriate)

No way of taking screenshots. However when it happens I can see the coursor still and move it. It's on the black screen. It then reboots after a few seconds

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: `LibreELEC (official): 10.0.0`

 - Kodi version: `19.1`

**Comment by Mariusz89B** [comment]
Thank you, I will look in to this issue.

**Comment by Mariusz89B** [comment]
@onicniepytaj Please check if the error still persists. https://github.com/Mariusz89B/script.mtvguide/commit/73f2719d7181aec3f37c9d7a08fbb27e05188f9e

https://github.com/Mariusz89B/script.mtvguide/releases/tag/9.8.2_v6

**Comment by onicniepytaj** [comment]
Hiya,
It's not crashing this time so the problem is fixed. However a minute or two after the incident now the add-on is making a refresher, it shows all the channels for like 5 seconds and then it all disappears. 
https://paste.ubuntu.com/p/VGy5JmNgk4/
This happened around 22:23.

**Comment by Mariusz89B** [comment]
@onicniepytaj Could you specify a bit more what is happening?

**Comment by Mariusz89B** [comment]
Bug fixed.
