### ISSUE TITLE
Difficulty Downloading

### ISSUE THREAD

**Issue by ColtCarson45** [Mariusz89B/script.mtvguide#9]
I cannot find the correct kodi source for the repository, I found one on Facebook but it will not allow me to download it. Please help, thanks

**Comment by ColtCarson45** [comment]
Or the direct download link for the add on

**Comment by Mariusz89B** [comment]
Hi, 

URL download link for the repository is available in wiki:
https://github.com/Mariusz89B/script.mtvguide/wiki

As for a add-on direct download, you can find it under assets in releases:
https://github.com/Mariusz89B/script.mtvguide/releases
